export const FIND_FRIENDS = 'FIND_FRIENDS';
export const FIND_ACCOUNTS = 'FIND_ACCOUNTS';
export const GET_UNIT_IDS = 'GET_UNIT_IDS';
export const FIND_UNIT = 'FIND_UNIT';
export const GET_GLOBAL_RECOMMENDATIONS = 'GET_GLOBAL_RECOMMENDATIONS';
export const GET_RECOMMENDATION = 'GET_RECOMMENDATION';
